name: Run Cypress Tests

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student PR code
        uses: actions/checkout@v2

      - name: List directory structure
        run: |
          ls -R

      - name: Install dependencies in student's repo
        run: |
          cd student-repo # or the correct subfolder where package.json is
          npm install
